lsi: false
safe: true
source: 'zenabawada.github.io'
incremental: false
highlighter: rouge
gist:
  noscript: false
kramdown:
  math_engine: mathjax
  syntax_highlighter: rouge
theme: minima
remote_theme: jekyll/minima
